name: Unit Test

on: 
  push:
    branches-ignore:    
      - 'master'
    tags-ignore:
      - v*
  pull_request:
    branches-ignore:    
      - 'master'

jobs:
  build_and_test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./swmm-toolkit

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            activate: ./build-env/Scripts/activate

          - os: macos-latest
            activate: source ./build-env/bin/activate
          
          - os: ubuntu-latest
            activate: source ./build-env/bin/activate

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheel in virtual env
        run: |
          python -m venv --clear ./build-env
          ${{matrix.activate}}
          python -m pip install -r build-requirements.txt
          python setup.py bdist_wheel
          deactivate

      - name: Test wheel
        run: |
          pip install -r test-requirements.txt
          pip install --no-index --find-links=./dist swmm_toolkit
          pytest
