name: Wheel build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_nrtest_plugin:
    name: Build nrtest-swmm plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nrtest-swmm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build wheel
        run: |
            pip install wheel
            python setup.py bdist_wheel
      
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: nrtest-swmm/dist/*.whl
