name: Wheel build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_nrtest_plugin:
    name: Build nrtest-swmm plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nrtest-swmm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build wheel
        run: |
            pip install wheel
            python setup.py bdist_wheel
      
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: nrtest-swmm/dist/*.whl


  build_swmm:
    name: Build SWMM
    runs-on: windows-2019
    defaults:
      run:
        shell: bash
        working-directory: swmm-toolkit/swmm-solver/ci-tools/linux

    steps:
    - name: Checkout swmm repo
      uses: actions/checkout@v3

    - name: Checkout ci-tools repo
      uses: actions/checkout@v3
      with:
        repository: michaeltryby/ci-tools
        ref: master
        path: swmm-toolkit/swmm-solver/ci-tools

    - name: Build
      run: |
        pwd
        ls -l
        make.sh -g "Visual Studio 16 2019"



